    wire sram4amen;
    wire bkpramamen;
    wire adc3amen;
    wire bdmaamen;
    wire crcamen;
    wire gpiokamen;
    wire gpiojamen;
    wire gpioiamen;
    wire gpiohamen;
    wire gpiogamen;
    wire gpiofamen;
    wire gpioeamen;
    wire gpiodamen;
    wire gpiocamen;
    wire gpiobamen;
    wire gpioaamen;
    wire sai4amen;
    wire rtcamen;
    wire vrefamen;
    wire comp12amen;
    wire lptim5amen;
    wire lptim4amen;
    wire lptim3amen;
    wire lptim2amen;
    wire i2c4amen;
    wire spi6amen;
    wire lpuart1amen;
    wire syscfgamen;
    assign rcc_sram4_amen = sram4amen;
    assign rcc_bkpram_amen = bkpramamen;
    assign rcc_adc3_amen = adc3amen;
    assign rcc_bdma_amen = bdmaamen;
    assign rcc_crc_amen = crcamen;
    assign rcc_gpiok_amen = gpiokamen;
    assign rcc_gpioj_amen = gpiojamen;
    assign rcc_gpioi_amen = gpioiamen;
    assign rcc_gpioh_amen = gpiohamen;
    assign rcc_gpiog_amen = gpiogamen;
    assign rcc_gpiof_amen = gpiofamen;
    assign rcc_gpioe_amen = gpioeamen;
    assign rcc_gpiod_amen = gpiodamen;
    assign rcc_gpioc_amen = gpiocamen;
    assign rcc_gpiob_amen = gpiobamen;
    assign rcc_gpioa_amen = gpioaamen;
    assign rcc_sai4_amen = sai4amen;
    assign rcc_rtc_amen = rtcamen;
    assign rcc_vref_amen = vrefamen;
    assign rcc_comp12_amen = comp12amen;
    assign rcc_lptim5_amen = lptim5amen;
    assign rcc_lptim4_amen = lptim4amen;
    assign rcc_lptim3_amen = lptim3amen;
    assign rcc_lptim2_amen = lptim2amen;
    assign rcc_i2c4_amen = i2c4amen;
    assign rcc_spi6_amen = spi6amen;
    assign rcc_lpuart1_amen = lpuart1amen;
    assign rcc_syscfg_amen = syscfgamen;
